spring:
  profiles:
    active: dev
---
server:
  port: 8001
mybatis:
  type-aliases-package: com.saowu.springcloud.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location:  classpath:mybatis/mybatis-config.xml

spring:
  profiles: dev
  application:
    name: springcloud-config-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.43.198:3306/db01?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: zdd123456

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept-8001
    prefer-ip-address: true


info:
  app.name: springcloud-provider-dept-8001
  company: www.saowu.top

---
server:
  port: 8001
mybatis:
  type-aliases-package: com.saowu.springcloud.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location:  classpath:mybatis/mybatis-config.xml

spring:
  profiles: test
  application:
    name: springcloud-config-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.43.198:3306/db02?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: zdd123456

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept-8001
    prefer-ip-address: true


info:
  app.name: springcloud-provider-dept-8001
  company: www.saowu.top