spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: springcloud-config-eureka

server:
  port: 7001

eureka:
  instance:
    #注册中心名字
    hostname: eureka7001.com
  client:
    #是否向注册中心注册
    register-with-eureka: false
    #要不要去注册中心获取其他服务的地址
    fetch-registry: false
    #监控页面
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka

---
spring:
  profiles: test
  application:
    name: springcloud-config-eureka

server:
  port: 7001

eureka:
  instance:
    #注册中心名字
    hostname: eureka7001.com
  client:
    #是否向注册中心注册
    register-with-eureka: false
    #要不要去注册中心获取其他服务的地址
    fetch-registry: false
    #监控页面
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
